import XCTest
@testable import DynamicIslandCore

final class CompatTests: XCTestCase {

    /// The symptom column is the reason the page exists — a dependency without one is a row that
    /// tells a person nothing when the thing it names breaks.
    func testEveryDependencyIsFilledIn() {
        for d in Compat.dependencies {
            XCTAssertFalse(d.what.isEmpty)
            XCTAssertFalse(d.source.isEmpty)
            XCTAssertFalse(d.symptom.isEmpty, "no symptom: \(d.what)")
            XCTAssertFalse(d.confirmed.isEmpty, "no confirmation: \(d.what)")
        }
    }

    func testThereIsSomethingToDocument() {
        XCTAssertGreaterThanOrEqual(Compat.dependencies.count, 10)
    }

    /// The page is printed from the list; anything the list holds has to reach it.
    func testTheMarkdownCarriesEveryDependency() {
        let md = Compat.markdown()
        for d in Compat.dependencies {
            XCTAssertTrue(md.contains(d.what), "missing from the page: \(d.what)")
            XCTAssertTrue(md.contains(d.symptom), "missing symptom: \(d.symptom)")
        }
    }

    func testOneTableRowPerDependency() {
        let rows = Compat.markdown()
            .split(separator: "\n")
            .filter { $0.hasPrefix("| ") && !$0.contains("---") && !$0.hasPrefix("| What ") }
        XCTAssertEqual(rows.count, Compat.dependencies.count)
    }

    /// It says so at the top, and it is the only thing standing between a generated page and
    /// somebody editing it by hand.
    func testThePageSaysItIsGenerated() {
        XCTAssertTrue(Compat.markdown().hasPrefix("<!-- Generated by"))
    }

    /// `confirmed` is either a measurement somebody wrote down, or the honest admission that
    /// nobody went back to find where it started. Inventing a version would make the column mean
    /// "probably".
    func testConfirmationIsEitherMeasuredOrHonestlyAssumed() {
        for d in Compat.dependencies {
            let ok = d.confirmed.contains("measured") || d.confirmed == "assumed"
            XCTAssertTrue(ok, "\(d.what) claims \(d.confirmed)")
        }
    }

    /// A pipe in a cell would split it into columns and quietly reshape the table.
    func testNoCellContainsAnUnescapedPipe() {
        for d in Compat.dependencies {
            for field in [d.what, d.source, d.symptom, d.confirmed] {
                XCTAssertFalse(field.contains("|"), "pipe in: \(field)")
            }
        }
    }
}
